### ISSUE TITLE
App Store Privacy Details are incorrect

### ISSUE THREAD

**Issue by OscarBouwmans** [aaronhma/ElonMigo#6]
The App Privacy label on the App Store says _Data Not Collected_. This is incorrect, as you state in the readme that the Gemini API may collect data. Third party data collection must also be reported, as per [Apple’s terms](https://developer.apple.com/app-store/app-privacy-details/):

> “Collect” refers to transmitting data off the device in a way that allows you and/or your third-party partners to access it for a period longer than what is necessary to service the transmitted request in real time.
“Third-party partners” refers to analytics tools, advertising networks, third-party SDKs, or other external vendors whose code you’ve added to your app.

The Privacy Details of Recap on the App Store should be updated to reflect the Gemini API’s terms, in order to avoid the app being taken down by Apple.

**Comment by Visual-Studio-Coder** [comment]
Hi Oscar!

This repository is no longer active and is outdated. Please follow the following official repository instead for future updates:

[__https://github.com/visual-studio-coder/qr-share-pro__](https://github.com/visual-studio-coder/qr-share-pro)

Visual-Studio-Coder (Vaibhav Satishkumar) is no longer affiliated with this fraudulent organization or its members and will no longer recognize any people from this organization claiming to have contributed to this repository or any of my other projects.

**Comment by OscarBouwmans** [comment]
It looked to me like some of the uses for Recap could fall under _“may be collected but not linked to your identity”_, but I must admit it has been a while since I have had to fill in the checkboxes…

Just trying to make sure your app is not violating any terms that could get it removed :)

**Comment by Visual-Studio-Coder** [comment]
This repository is no longer active and is outdated. Please follow the following official repository instead for future updates:

[__https://github.com/visual-studio-coder/qr-share-pro__](https://github.com/visual-studio-coder/qr-share-pro)

Visual-Studio-Coder (Vaibhav Satishkumar) is no longer affiliated with this fraudulent organization or its members and will no longer recognize any people from this organization claiming to have contributed to this repository or any of my other projects.
